
package com.sdp.edu.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestServiceInfService", targetNamespace = "http://server.edu.sdp.com/", wsdlLocation = "http://localhost:8080/webservice_server_test/test?wsdl")
public class TestServiceInfService
    extends Service
{

    private final static URL TESTSERVICEINFSERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTSERVICEINFSERVICE_EXCEPTION;
    private final static QName TESTSERVICEINFSERVICE_QNAME = new QName("http://server.edu.sdp.com/", "TestServiceInfService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/webservice_server_test/test?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTSERVICEINFSERVICE_WSDL_LOCATION = url;
        TESTSERVICEINFSERVICE_EXCEPTION = e;
    }

    public TestServiceInfService() {
        super(__getWsdlLocation(), TESTSERVICEINFSERVICE_QNAME);
    }

    public TestServiceInfService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTSERVICEINFSERVICE_QNAME, features);
    }

    public TestServiceInfService(URL wsdlLocation) {
        super(wsdlLocation, TESTSERVICEINFSERVICE_QNAME);
    }

    public TestServiceInfService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTSERVICEINFSERVICE_QNAME, features);
    }

    public TestServiceInfService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestServiceInfService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestServiceInf
     */
    @WebEndpoint(name = "TestServiceInfPort")
    public TestServiceInf getTestServiceInfPort() {
        return super.getPort(new QName("http://server.edu.sdp.com/", "TestServiceInfPort"), TestServiceInf.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestServiceInf
     */
    @WebEndpoint(name = "TestServiceInfPort")
    public TestServiceInf getTestServiceInfPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.edu.sdp.com/", "TestServiceInfPort"), TestServiceInf.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTSERVICEINFSERVICE_EXCEPTION!= null) {
            throw TESTSERVICEINFSERVICE_EXCEPTION;
        }
        return TESTSERVICEINFSERVICE_WSDL_LOCATION;
    }

}
